# #######################################################################################
# "pnpm install" composite action                                                       #
# --------------------------------------------------------------------------------------#
#                                                                                       #
# Usage in workflows steps:                                                             #
#                                                                                       #
#      - name: 📥 PNPM install                                                          #
#        uses: ./.github/actions/pnpm-install                                           #
#                                                                                       #
# Reference:                                                                            #
#   - latest: https://github.com/pnpm/action-setup#use-cache-to-reduce-installation-time#
# #######################################################################################

description: Run pnpm install with cache enabled

name: PNPM install

runs:
  steps:
    - name: Configure Git
      uses: ./.github/actions/git-config

    - name: Install pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
      with:
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
      with:
        cache: pnpm
        node-version-file: .nvmrc

    - env:
        # Other environment variables
        HUSKY: "0" # By default do not run HUSKY install
      name: Install dependencies
      run: pnpm install --frozen-lockfile --prefer-offline
      shell: bash
      working-directory: ${{ inputs.cwd }}

  using: composite
